### ISSUE TITLE
Encoding image returns null

### ISSUE THREAD

**Issue by AmirHosseinKarimi1997** [sungaila/PDFtoImage#109]
### Question

Hi, 
I use this library on a Windows container to convert pdf to images.
There is one scenario happening and unfortunately, I don't have access to the file to reproduce it myself.

after converting the pdf to images, I loop through the images and for each I call Encode method to get the image and store it somewhere. But for some images, the Encode method returns null. I don't have the file myself to reproduce it, so I was wondering if you could help with some tips to fix/identify the issue.

Here is the code I am using:

`

    private async Task ConvertAndStorePreviewImagesFromPdf(string pdfPath, float ratio, ITextDocument textDocument, PreviewSetting[] previewsSettings)
    {
        var pdf = await File.ReadAllBytesAsync(pdfPath);

        foreach (var previewSetting in previewsSettings)
        {
            var height = (int)(previewSetting.Width / ratio);
            var options = new RenderOptions(Width: previewSetting.Width, Height: height);
            var images = Conversion.ToImages(pdf, options: options);

            await StorePreviews(images, textDocument, previewSetting);
        }
    }

    private async Task StorePreviews(IEnumerable<SKBitmap> previews, ITextDocument textDocument, PreviewSetting previewSetting)
    {
        foreach (var image in previews)
        {
            using var data = image.Encode(SKEncodedImageFormat.Png, 100); // Quality range from 0-100
            // storing and calling data.ToArray() and here is where the exception happens.
            image.Dispose();
        }
    }
`

Any help is appreciated.

**Comment by sungaila** [comment]
Hi @AmirHosseinKarimi1997,

so PDFtoImage returned a `SKBitmap` but calling `Encode` results in `null`? Is it happening just for certain images 100% of the time?

Either the returned bitmap is corrupted (pdfium or PDFtoImage failed) or SkiaSharp failed to encode the image. This is just guessing and we would need an example image to reproduce this issue.

**Comment by AmirHosseinKarimi1997** [comment]
Hi again, thanks and sorry for taking your time.
I managed to find one of the documents and the issue was related to getting the ratio. We were passing height 0 to the options here:
`var images = Conversion.ToImages(pdf, options: options);`
It resulted in an empty byte array. All good after fixing the ratio.

**Comment by sungaila** [comment]
Good to know! But I should throw an ArgumentOutOfRangeException when width or height is set to 0.

I'll add this in a future release.

**Comment by AmirHosseinKarimi1997** [comment]
That makes sense.
Thanks.
