### ISSUE TITLE
AOT issue

### ISSUE THREAD

**Issue by Bxaa** [sungaila/PDFtoImage#14]
Thx for project!
Sadly issue:
PDFtoImage.Conversion.GetPageCount and PDFtoImage.Conversion.ToImage cause deadlock (permanent loop) after AOT compilation
(Tested with all version AOT native)

**Comment by sungaila** [comment]
Hi @Bxaa,

what kind of AOT do you mean? Do you mean ReadyToRun? Do you mean the new AOT from the .NET 7 previews?

Can you give me a sample project to test this myself?

**Comment by Bxaa** [comment]
I mean Native AOT (https://github.com/dotnet/runtimelab/tree/feature/NativeAOT)
Used 6.0.0-rc.1.21373.1 (other versions with parallel invoke implementation\type issue)

FOR TEST:
https://drive.google.com/file/d/16pLGLsXNfGq0zZYd-wLDqELkn48neVB4/view?usp=sharing

Need check all your pinvoke's:
I think issue can be fixed by <MarshalAs(UnmanagedType.LPWStr)>for strings with CharSet:=CharSet.Unicode for some pinvokes MarshalAs(UnmanagedType.LPArray)> and <MarshalAs(UnmanagedType.Bool)> ,etc
Also: need check some pinvoke return value (i got issue with null terminated strings for some pinvokes and AOT. Possible we have same issue)
(return values is some String + chr(0) + chr(0)+ chr(0)+ chr(0)+ chr(0)...etc)
So need trim string end with chr(0)

```
//Just example:
This declaration crash app after AOT
 <DllImport("Kernel32.dll", EntryPoint:="GetFinalPathNameByHandle", SetLastError:=True, CharSet:=CharSet.ANSI)>
        Public Shared Function GetFinalPathNameByHandle(ByVal hFile As IntPtr,
        ByVal lpszFilePath As StringBuilder, ByVal cchFilePath As UInteger, ByVal dwFlags As UInteger) As UInteger
        End Function
---
//Correct declaration is:
 <DllImport("Kernel32.dll", EntryPoint:="GetFinalPathNameByHandle**W**", SetLastError:=True, CharSet:=CharSet.**Unicode**)>
        Public Shared Function GetFinalPathNameByHandle(ByVal hFile As IntPtr,
        <**MarshalAs(UnmanagedType.LPWStr)**> ByVal lpszFilePath As StringBuilder, ByVal cchFilePath As UInteger, ByVal dwFlags As UInteger) As UInteger
        End Function
```
Thx

**Comment by Bxaa** [comment]
And.. yes, all SkiaSharp.dll functions work fine after AOT except PDFtoImage.Conversion.GetPageCount and PDFtoImage.Conversion.ToImage
(Some issue with PDFtoPNG nuget)

**Comment by sungaila** [comment]
Thanks for providing additional information. I'll be looking into it!

**Comment by sungaila** [comment]
I checked the crash dump and found that pdfium.dll is crashing with the exception code `0xC0000005` (access violation reading `0xFFFFFFFFFFFFFFFF`). This happens when the PDF document is loaded by calling the native method `FORM_DoDocumentOpenAction`.

Since I haven't much experience in unmanaged C development (and not having the debug symbols for PDFium 105.0.5131 ready), I will give up further investigations here. My guess is that something is wrong in PDFium or even NativeAOT.

I'll gladly accept your pull request, @Bxaa, if you succeed in fixing this issue!

**Comment by Bxaa** [comment]
Thx, for testing. I'll try to investigate it.
I'll try to figure it out (it will be pretty hard to do...)
I'll let you know if I succeed.

**Comment by Bxaa** [comment]
You need pdfium.dll 4648.0.0 (native PDFium.x64 without V8 or XFA support) and x64 libSkiaSharp.dll (look in nuget both)
(AOT only support x64)
Both should be in same folder with native compiled exe
-or-
You can include dll's to native exe (with some tricks)

That's all :)

**Comment by Bxaa** [comment]
@[sungaila](https://github.com/sungaila)
```
static NativeMethods()
        {
            // Load the platform dependent Pdfium.dll if it exist.
            var workingDirectory =
                Assembly.GetExecutingAssembly().GetName(false).CodeBase
                ?? Process.GetCurrentProcess().MainModule!.FileName!;

            LoadNativeLibrary(Path.GetDirectoryName(new Uri(workingDirectory).LocalPath)!);
        }
```
In this case all dlls search redirects ignored and possible cause issues with .NET deployment and custom settings for assemblies and native dll's embedded deployment
          
For Windows NETFRAMEWORK and NETCOREAPP3_1_OR_GREATER you should use Dynamic-Link Library Search Order for native DLL (GetDllDirectory max priority):
```
---\\---\\---
string workingDirectory = Path.GetFullPath(Assembly.GetExecutingAssembly().GetName(false).CodeBase ?? Process.GetCurrentProcess().MainModule!.FileName!);
            StringBuilder tmp = new StringBuilder(32767); //32767 long path
            if (NativeMethods.GetDllDirectory(32767, tmp) == true && tmp.ToString() != string.Empty) //Return empty string if not set
            {
                if (File.Exists(Path.Combine(Path.GetFullPath(tmp.ToString()), "pdfium.dll")))
                {
                    workingDirectory = Path.GetFullPath(tmp.ToString());
                }
            }
            LoadNativeLibrary(Path.GetDirectoryName(new Uri(workingDirectory).LocalPath)!);
---\\---\\---
public class NativeMethods
{
    [DllImport("kernel32.dll", CharSet = CharSet.Unicode, SetLastError = true)]
    [return: MarshalAs(UnmanagedType.Bool)]
    static public extern Boolean GetDllDirectory(int nBufferLength, [MarshalAs(UnmanagedType.LPWStr)] StringBuilder lpPathName);
}
```
Also you can add check path from Environments DOTNET_BUNDLE_EXTRACT_BASE_DIR as second in order

**Comment by sungaila** [comment]
> You need pdfium.dll 4648.0.0 (native PDFium.x64 without V8 or XFA support) and x64 libSkiaSharp.dll (look in nuget both) (AOT only support x64) Both should be in same folder with native compiled exe -or- You can include dll's to native exe (with some tricks)

This did not work for me. I used those native libs and the program will still crash:

- https://www.nuget.org/packages/PDFium.x64/4648.0.0
- https://www.nuget.org/packages/SkiaSharp.NativeAssets.Win32/2.88.0

**Comment by Bxaa** [comment]
@sungaila 
Hi,
https://drive.google.com/file/d/1txkmoSjA7ttLGkFTwNUnDbzR1XGn2exS/view?usp=sharing
This is fix for you NativeMethods.cs (just replace it in your repository)
If you want I can add a fully automatic deploy module for native dll's (it make a your pdftoimage fully portable on windows)

Also i include to archive v_Comparator.exe (fully native exe with your pdftoimage assembly for test)
(Single exe)

**Comment by Bxaa** [comment]
@sungaila 
```
**public** sealed class PdfException : Exception
    {
        **public** PdfError Error { get; private set; }
```
---\\---\\---
and

```
**public** enum PdfError
    {
        Success = (int)NativeMethods.FPDF_ERR.SUCCESS,
        Unknown = (int)NativeMethods.FPDF_ERR.UNKNOWN,
---\\---\\---
```
This will make possible normally handle error from main app (PDFtoImage.PdfiumViewer.PdfException)

Example:
PdfError.PasswordProtected

**Comment by Bxaa** [comment]
@sungaila Possible bug passworded pdf's
 'Password required or incorrect password'

Reproduce:
PDFtoImage.Conversion.GetPageCount(Base_64_String_Pdf_String, "test")

Sample PDF (password: test)
https://drive.google.com/file/d/1QF2U0o98qZ5U1G0rhCfrq0Va3hOvhZBg/view?usp=sharing

(Maybe it's just me having a glitch with the AOT or pdfium.dll version)
