### ISSUE TITLE
Color was not correct

### ISSUE THREAD

**Issue by leeichang** [sungaila/PDFtoImage#17]
I use PDFtoImage to Convert PDF file first page to PNG image
This is the original Pdf screenshot.
<img width="964" alt="Original Pdf screenshot" src="https://user-images.githubusercontent.com/853914/191651361-1196e37b-9ba2-484b-94cd-f8fd56cf0399.png">
This is the convert result
![Convert Image](https://user-images.githubusercontent.com/853914/191651457-4d8171eb-1d18-4e68-902f-3565433512e9.png)
This is the original Pdf file
[322145774-Coca-Cola-by-Group-5.pdf](https://github.com/sungaila/PDFtoImage/files/9621916/322145774-Coca-Cola-by-Group-5.pdf)
**You can see the color was not right. 
How can I fix it?**
Here is my code

```
            using var inputStream = new FileStream(inputFile, FileMode.Open, FileAccess.Read);
            string outputPath = Path.Combine(outputFolder, outputFileName + "_200.png");
            Conversion.SavePng(outputPath, inputStream, null, 0, 600, 200, 200);
```

**Comment by sungaila** [comment]
Hi @leeichang,

thank you for opening this issue! Can you please tell me on which platform (Windows, Linux, macOS, Android) and architecture (x86, x64, ARM64) you have tested this?

**Comment by leeichang** [comment]
I used macOS M1 ARM64 but Windows x64 the same, I have both Mac M1 and Hp Windows 10 notebook.
