### ISSUE TITLE
System.DllNotFoundException: '/data/data/com.companyname.pos.apphost/files/.__override__/runtimes/android-x64/native/libpdfium.so'

### ISSUE THREAD

**Issue by hosamyousof** [sungaila/PDFtoImage#20]
I'm testing PDFtoImage.Conversion.ToImage() in .NET MAUI project that targets windows and android.
It works fine in windows platform but throws an exception in android:

System.DllNotFoundException: '/data/data/com.companyname.pos.apphost/files/.__override__/runtimes/android-x64/native/libpdfium.so'

I'm testing on Android Emulator: Android 12.0 - API 31
![image](https://user-images.githubusercontent.com/16549201/213488789-9fa89e5e-a313-4e15-8aba-75b9e11028da.png)

I installed PDFtoImage v2.1.2

Can you please help me solve this issue.

Best regards,

**Comment by sungaila** [comment]
Hi @hosamyousof,

what is the `TargetFramework` of this .NET MAUI project? Both `net6.0-android31.0` and `MonoAndroid 10.0` should include the needed Android binaries.

If it's just `net6.0` (or newer) you must add those two missing NuGet packages on your own:
- https://www.nuget.org/packages/bblanchon.PDFium.Android/
- https://www.nuget.org/packages/SkiaSharp.NativeAssets.Android/

**Comment by sungaila** [comment]
How does the bin folder look like? Is there `runtimes/android-x64/native/libpdfium.so` copied to the output folder? Or is there a `libpdfium.so` in the root folder of the output?

**Comment by hosamyousof** [comment]
I think you mean the target framework should be: `net6.0-android31.0` or later not `net6.0-android21.0`
Like mentioned in this warning:
![image](https://user-images.githubusercontent.com/16549201/213504905-7b14a134-5939-4010-8b23-1c97415ac8a8.png)

I changed the target framework to `net6.0-android31.0` and tried but I'm getting the same exception.

Regarding the bin folder:
It looks like this
![image](https://user-images.githubusercontent.com/16549201/213516558-1688303a-67b8-4a3c-830e-5a01aed479a6.png)

**Comment by sungaila** [comment]
I tested .NET MAUI with Android and found the code for loading the libpdfium.so was not working.

Could you please give [PDFtoImage 2.1.3](https://www.nuget.org/packages/PDFtoImage/2.1.3) a try?

**Comment by hosamyousof** [comment]
I appreciate your instance response @sungaila

I've updated the library to 2.1.3 and It's working fine. 

Thank you.
