### ISSUE TITLE
Document and example missing.

### ISSUE THREAD

**Issue by Adi-18** [sungaila/PDFtoImage#26]
Document and example missing (VB.NET, C#).
I.e.:
-  How to work
- How convert to Images or Bitmap (not SKBitmap)
- etc.

**Comment by slaners** [comment]
Do you understand how to use it?
I tried to use it, but it reminded me “The type initializer for 'PDFtoImage.PdfiumViewer.NativeMethods' threw an exception.”

my code
FileStream fSm = new(filePath, FileMode.Open);
var imgObj = PDFtoImage.Conversion.ToImages(fSm);

**Comment by sungaila** [comment]
Hi @slaners,

could you please add the full stack trace and which OS you tried this on?

**Comment by slaners** [comment]
> 你好@slaners,
> 
> 您能否添加完整的堆栈跟踪以及您在哪个操作系统上尝试过？

I'm sorry, I've been busy recently, I recreated a project to prevent other incompatibilities, I used the previous code, and now it works fine.

**Comment by sungaila** [comment]
@slaners Glad to hear that! Please reopen this issue if you encounter another problem.
