### ISSUE TITLE
Hope to optimize it

### ISSUE THREAD

**Issue by xizhengchao** [sungaila/PDFtoImage#41]
Through testing, LoadLibrary dll call to pdfium performs better than DllImport, especially during batch processing

**Comment by sungaila** [comment]
Hello @xizhengchao,

thank you for your feedback! I am not sure what you mean exactly. For .NET Framework the Win32 API `LoadLibrary` is called. For .NET (Core) the function `System.Runtime.InteropServices.NativeLibrary.Load` is called instead.

Could you please give me a code example on what you would like to change?

**Comment by xizhengchao** [comment]
Hello,Your project is very good, which is what I want. However, as it belongs to I/O operations, there may be consumption when calling NativeMethods. It is recommended to use generate a call delegate for c # by observing points to functions in DLL/so in conjunction with LoadLibrary, especially in NET (Core),Maybe this will require more workload

**Comment by sungaila** [comment]
Thank you for clarifying! `DllImportAttribute` is expensive and going with Win32 LoadLibrary and unmanged function pointers would improve performance on Windows machines, yes.

However, this library targets .NET Framework 4.6.2, .NET Framework 4.8.1, .NET 6, .NET 7, .NET 7 for Android and Xamarin.Android 10. I would have to add many `#if NET6_0_OR_GREATER` conditionals and checks if the current machine is running Windows. I am not convinced if this effort is worth it.

[There is one unmanaged function pointer in this project right now.](https://github.com/sungaila/PDFtoImage/blob/a1f57f5fbc5029f3ba347a6395cc780a8b0f47a2/src/PDFtoImage/PdfiumViewer/NativeMethods.Pdfium.cs#L585C4-L585C82) This was however added for WebAssembly and not for performance reasons.

**Comment by entregadoronline** [comment]
This lib is incredible, but it is absolutely cpu bound, I am using it to batch process more than 500 thousand PDF files per week, and the amount of CPU it consumes is absurd, it is almost becoming unfeasible to use it.
The "PDFtoImage.Conversion.ToImage" method not being async causes api calls to become blocking and then the entire container stops responding.
I'm trying to think of an alternative, but so far without success.
Any sugestion?
![image](https://github.com/sungaila/PDFtoImage/assets/67846005/5a38a5dd-96f2-44ae-b141-b58057529c5e)

**Comment by tucomel** [comment]
This lib is incredible, but it is absolutely cpu bound, I am using it to batch process more than 500 thousand PDF files per week, and the amount of CPU it consumes is absurd, it is almost becoming unfeasible to use it.
The "PDFtoImage.Conversion.ToImage" method not being async causes api calls to become blocking and then the entire container stops responding.
I'm trying to think of an alternative, but so far without success.
Any sugestion?

![image](https://github.com/sungaila/PDFtoImage/assets/8607299/8b04a987-20d6-4b23-ae96-5277d57ed2e0)

**Comment by sungaila** [comment]
@tucomel This library is a wrapper of [PDFium](https://pdfium.googlesource.com/pdfium/) which is not thread-safe. Meaning you can render one PDF file per process at a time only.

>That's correct. PDFium is not thread safe. Why do you want to make it
thread safe though? If you are trying to render multiple documents,
you can just run multiple PDFium processes instead. That's what we do
for PDFium's corpus tests.
https://groups.google.com/g/pdfium/c/HeZSsM_KEUk/m/vO-8W378BQAJ

You can put the rendering into it's own thread though. Just wrap it with `Task.Run` or call `PDFtoImage.Conversion.ToImagesAsync`.

PDFium has no GPU acceleration (which shouldn't be of much help in a container anyway).
