### ISSUE TITLE
Support of .NET 7 MAUI

### ISSUE THREAD

**Issue by fhintsch** [sungaila/PDFtoImage#42]
I tried the „PdfToImage“-Package in a .NET 7 MAUI environment. I want to target all MAUI supported platforms (Android, iOS, macOS, Windows). This package seems to be great work, but unfortunately using `PDFtoImage.Conversion.SavePng(img, pdfStream, height: 300)` throws an Exception 

	{System.NotSupportedException: Only win-x86, win-x64, win-arm64, linux-x64, linux-arm, linux-arm64, osx-x64, and osx-arm64 are supported.    at PDFtoImage.PdfiumViewer.NativeMethods.LoadNativeLibraryNetCore(String path)    at PDFtoImage.PdfiumViewer.NativeMetho…}

Do you have any plans to make this package work for the .NET 7 MAUI platform?

**Comment by sungaila** [comment]
Hello @fhintsch, supporting Android and iOS for the `net7.0` target framework shouldn't be an issue. However, I don't have the necessary hardware to test iOS.

**Comment by sungaila** [comment]
@fhintsch Where did you get this exception? Android, iOS, macOS or any combination of them?

**Comment by fhintsch** [comment]
I got it on macOS, the target is called "MacCatalyst".

**Comment by sungaila** [comment]
There is support for iOS now (#98) but still no support for macOS (Mac Catalyst).

I'll close this issue in favor of #52 because the other one has more context on what is missing.
