### ISSUE TITLE
Opening Pdfs with Password fails

### ISSUE THREAD

**Issue by kumar-vasan** [sungaila/PDFtoImage#43]
[09 September 15 th July PW 6BA065200.pdf](https://github.com/sungaila/PDFtoImage/files/12715283/09.September.15.th.July.PW.6BA065200.pdf)
While making a call to *ToImage* method in *Conversion* with the correct password  as shown below
---
*using var inputStream = new FileStream(pdfFilePath, FileMode.Open, FileAccess.Read);
var image = Conversion.ToImage(inputStream, password, page: 0);*

the code fails with the an Exception **PDFtoImage.PdfiumViewer.PdfException**: 'Password required or incorrect password'

at line 30 in file PDFtoImage\PdfiumViewer\PdfFile as after call to *NativeMethods.FPDF_LoadCustomDocument* in line 28

*var document = NativeMethods.FPDF_LoadCustomDocument(stream, password, _id);
if (document == IntPtr.Zero)
    throw new PdfException((PdfError)NativeMethods.FPDF_GetLastError());*
    
 *Attached a PDF file with password to test. Please use password **6BA065200** to test

**Comment by sungaila** [comment]
Hi @kumar-vasan, thank you for reporting this! I could reproduce this issue and am working on a bugfix.

**Comment by sungaila** [comment]
@kumar-vasan [PDFtoImage 2.4.1](https://www.nuget.org/packages/PDFtoImage/2.4.1) is available now, please give it a try!

**Comment by kumar-vasan** [comment]
Thanks a lot @sungaila .
