### ISSUE TITLE
MAUI .NET 7: Converting pdf stream to image in Release mode throws an exception

### ISSUE THREAD

**Issue by AndriyGlodan** [sungaila/PDFtoImage#45]
Hello, I started using your package for converting PDF stream to SKBitmap image. And it works well in Debug mode. But when I installed my app in Release mode, it throws an exception. Here is the stack trace. Any thoughts?
<img width="980" alt="image" src="https://github.com/sungaila/PDFtoImage/assets/48009762/16a616ab-ebba-4bcc-8e1f-d3eebe2ebb7d">

**Comment by AndriyGlodan** [comment]
Do you need a sample project?

**Comment by sungaila** [comment]
> Do you need a sample project?
Sure, a minimal sample project would be much appreciated!

**Comment by AndriyGlodan** [comment]
Take this one
[PdfToImageExample.zip](https://github.com/sungaila/PDFtoImage/files/12868359/PdfToImageExample.zip)

**Comment by sungaila** [comment]
@AndriyGlodan Thanks, I could reproduce this issue and am looking into the cause of this problem.

**Comment by AndriyGlodan** [comment]
OK. Thanks a lot!

**Comment by sungaila** [comment]
[PDFtoImage 2.4.2](https://www.nuget.org/packages/PDFtoImage/2.4.2) went live. @AndriyGlodan could you please check if your issue was solved?

Please note that this library does not support iOS/Mac Catalyst yet. This might become a problem if you want to target these platforms with your MAUI app.

**Comment by sungaila** [comment]
> Could you update the PdfToZpl library so it'll use the latest version of the PdfToImage library?

[Already done.](https://www.nuget.org/packages/PDFtoZPL/3.6.2) ;-)
