### ISSUE TITLE
Anti-Alias being applied causing distortion to barcodes

### ISSUE THREAD

**Issue by markbeazley** [sungaila/PDFtoImage#53]
### Question

Not sure if its a problem with this library, or an issue with PDFium or I'm just not getting the right combination of parameters. 

I'm trying to print shipment labels to a Zebra GK420d printer (203dpi), using [PDFtoZPL](https://github.com/sungaila/PDFtoZPL) and I've got it mostly working, however I noticed some issues with the 2D datamatrix barcode, where the elemets are rounded instead of square, I think I've found the culprit being the PDF to Image conversion, using this code

```csharp
var pdfBytes = File.ReadAllBytes("example-label.pdf");

var images = PDFtoImage.Conversion.ToImages(pdfBytes, dpi:203, width:812, height:1218);

foreach (var image in images)
{
    var data = image.Encode(SKEncodedImageFormat.Png, 100);
    File.WriteAllBytes("label-test.png", data.Span.ToArray());
}
```

It seems anti-aliasing has been applied
![image](https://github.com/sungaila/PDFtoImage/assets/17005579/d436913c-0399-4ca3-a532-0ae967d1e315)
 Which is fine for the text elements of the label, but could result in issues reading the barcodes, especially after the image goes through the Image to ZPL conversion, although that might be tweak-able by adjusting the threshold value, but seems a bit to fragile to rely on. I thought it might be related to the scaling caused by the dpi, height and width settings, and removing those 3 from the above code seems to remove the anti-aliasing from the 2D datamatrix, but not the rest of the label, which is just plain confusing.
![image](https://github.com/sungaila/PDFtoImage/assets/17005579/7a39b589-7913-4585-88a2-0d7fb7d3cba5)

[Original PDF file, 300dpi formatted to print on 4inch * 6 inch labels](https://github.com/sungaila/PDFtoImage/files/13786345/example-label.pdf)

PNG file generated by above code
![label-test](https://github.com/sungaila/PDFtoImage/assets/17005579/ed2013ea-558b-4354-aa10-da0b7d20bcad)

PNG file generated by above code with dpi,width and height not set
![label-test-no-params](https://github.com/sungaila/PDFtoImage/assets/17005579/4c651549-01ff-4d38-845b-85155e468a67)

**Comment by sungaila** [comment]
Hi @markbeazley, the scaling is handled by PDFium. [There are special flags for disabling anti-aliasing for text, images and paths](https://github.com/Dtronix/PDFiumCore/blob/94588dd3484d0717763f40245d497266f7e6da78/src/PDFiumCore/RenderFlags.cs#L43C9-L57C41) that are not available in PDFtoImage/PDFtoZPL yet.

I'll test these flags and expose them as new optional parameters. I'll inform you as soon as there is something to test.

**Comment by sungaila** [comment]
So I've been digging into the render flags and noticed a bug that would explain your weird results: If both `width` and `height` are unset, the anti-aliasing on images is disabled (but not for text or paths).

This was not intended and I'm working on a fix right now.

**Comment by sungaila** [comment]
Hey @markbeazley, I'll introduce `PDFtoImage.PdfAntiAliasing` to control which parts should be anti-aliased. For compatibility reasons it defaults to `PdfAntiAliasing.All`.

You can test these new flags here (make sure to clear your browser cache): https://www.sungaila.de/PDFtoImage/

Here is how each flag affects your example PDF. Please note that your barcode is text using the `IDAutomationC128XL` font. So there is no way to turn off anti-aliasing for text and barcode individualy.

### PDFtoImage.PdfAntiAliasing.Text
```csharp
PDFtoImage.Conversion.ToImages(pdfBytes, width:812, height:1218, antiAliasing: PDFtoImage.PdfAntiAliasing.Text);
```
![example-label_text](https://github.com/sungaila/PDFtoImage/assets/12021771/e5255f0d-f56a-4ef5-a481-5febc0e3d49b)

### PDFtoImage.PdfAntiAliasing.Images
```csharp
PDFtoImage.Conversion.ToImages(pdfBytes, width:812, height:1218, antiAliasing: PDFtoImage.PdfAntiAliasing.Images);
```
![example-label_images](https://github.com/sungaila/PDFtoImage/assets/12021771/7ba68a37-465a-4f9f-9479-7c18a6e8459b)

### PDFtoImage.PdfAntiAliasing.Paths
```csharp
PDFtoImage.Conversion.ToImages(pdfBytes, width:812, height:1218, antiAliasing: PDFtoImage.PdfAntiAliasing.Paths);
```
![example-label_paths](https://github.com/sungaila/PDFtoImage/assets/12021771/28d6b302-1cab-4d95-9d54-25b9f3a06ea7)

**Comment by markbeazley** [comment]
Hi @sungaila that's brilliant thanks, updated to the new nuget packages and it works perfectly.
