### ISSUE TITLE
Text missing when render pdf into image

### ISSUE THREAD

**Issue by scegg** [sungaila/PDFtoImage#55]
### PDFtoImage version

3.0.0

### OS

Windows

### Architecture

x64

### Framework

.NET (Core)

### Detailed bug report

```
using (var pdfStream = File.OpenRead(pdfFile))
            {
                PDFtoImage.Conversion.SavePng("D:\\output.png", pdfStream);
            }
```
[1.pdf](https://github.com/sungaila/PDFtoImage/files/13792212/1.pdf)
When processing the pdf attached, all texts are missing in the lower part of the image created. Png file is too big to upload.

**Comment by sungaila** [comment]
Hi @scegg, I can confirm the lower part of the PDF is not rendered correctly. I'll be looking into this issue.

**Comment by sungaila** [comment]
It looks like a memory issue. Your PDF is rendered at 300 DPI (default values) and is 4,000 * 46,812 in size.

That makes (4,000 * 46,812) px * 4 bytes/px = 748,992,000 bytes ≈ **749 megabytes**.

If you lower the DPI the text renders properly again:

```csharp
using (var pdfStream = File.OpenRead(pdfFile))
{
	PDFtoImage.Conversion.SavePng("D:\\output.png", pdfStream, dpi: 200);
}
```

![image](https://github.com/sungaila/PDFtoImage/assets/12021771/c9b4fa67-5357-4741-a5a4-ae0eb467b073)
![image](https://github.com/sungaila/PDFtoImage/assets/12021771/86a31436-58bf-43e9-a48b-2340cbd3f172)

I'll check if there are options in PDFium or SkiaSharp to circumvent this memory issue.

**Comment by sungaila** [comment]
I agree with you that an Exception should be thrown instead of generating corrupted images. However, this library is a wrapper of SkiaSharp and PDFium so there is little I can do about this.

For testing I replaced SkiaSharp with System.Common.Drawing (GDI) but the font issue is still there. This confirms that the issue must be related to PDFium.

Right now I am checking if there is any workaround or setting to fix this issue in PDFium.

**Comment by sungaila** [comment]
Unfortunately, I haven't found a way to work around this issue or detecting it in the first place.

**Comment by sungaila** [comment]
@scegg Good news: I did find a workaround after all! You can use the optional parameter `UseTiling` to render your sample PDF properly (text isn't missing anymore).

```csharp
using (var pdfStream = File.OpenRead(pdfFile))
{
	PDFtoImage.Conversion.SavePng("D:\\output.png", pdfStream, options: new(UseTiling: true));
}
```

With this parameter, the PDF is rendered in several parts and combined into one complete image at the end. This circumvents the issue of PDFium failing at very high resolutions.
