### ISSUE TITLE
Render predefined area instead of the entire pdf page to receive a subset of the pdf page as an image

### ISSUE THREAD

**Issue by ynnob** [sungaila/PDFtoImage#63]
### Detailed feature request

At the moment all methods to save the pdf page as an image render the entire page using X:0  and Y:0 as their origin.
If i only want a subset of the pdf as an image file i need to postprocess the image.

```
            using (MemoryStream pdfStream = new MemoryStream(resultPdfBytes))
            {
                SkiaSharp.SKBitmap bitmap = PDFtoImage.Conversion.ToImage(pdfStream);
                bitmap.ExtractSubset(bitmap, new SkiaSharp.SKRectI(0, 0, 1000, 1000));

                var data = bitmap.Encode(SkiaSharp.SKEncodedImageFormat.Png, 100);
                if(data is not null)
                {
                    resultPdfBytes = data.ToArray();
                }
            }
```

This is a time consuming process for very large pdf pages and not necessary if all methods would accept a Rect or x,y coordinates as their render origin + width / height. But it would probably be better to just pass a rectangle that defines the area the pdfium viewer should render.

Additionally rendering a very large pdf (for example large building plans) the rendering might fail. I have reproduced this multiple times by setting a dpi higher then 350 which in one case always fails to render. Rendering a subset should also solve this problem and allow rendering of areas with a higher dpi on a large pdf pages with a predefined rendering area.

I think this should be fairly easy to implement since both methods already expose left and top parameters which are set to 0 as default atm. (PDFtoImage.PdfiumViewer.PdfDocument.Render())
```
FPDFBitmap_FillRect()
RenderPDFPageToBitmap()
```

Greetings ynnob!

**Comment by sungaila** [comment]
Hi @ynnob, `FPDF_RenderPageBitmap` does not support clipping but `FPDF_RenderPageBitmapWithMatrix` looks like it does. I'm looking into it ...

**Comment by sungaila** [comment]
Hey @ynnob, I've released a preview version with support to render a subset of the PDF: [PDFtoImage 4.0.0-preview](https://www.nuget.org/packages/PDFtoImage/4.0.0-preview)

You can define the boundaries for the render with the `Bounds` parameter. The following example renders the bottom left quadrant of the PDF:

```csharp
// get the size of the first PDF page
var pageSize = PDFtoImage.Conversion.GetPageSize(pdfStream, leaveOpen: true, page: 0);

// render the bottom left quadrant
PDFtoImage.Conversion.SavePng("output.png", pdfStream, page: 0, options: new(Dpi: 300, Bounds: new(0, pageSize.Height / 2f, pageSize.Width / 2f, pageSize.Height / 2f)));
```

Please note that the `Bounds` are relative to the size returned by `GetPageSize` and is independent to your `Dpi`, `Width`, `Height` and other settings. Rendering a subset of the PDF **will not** shrink the output image, you have to calculate the new size yourself.

You can test this new option here: https://www.sungaila.de/PDFtoImage/

Please let me know if this feature is working as expected so I can build a final release later on.

**Comment by ynnob** [comment]
Jeah the roatation is no problem. We already have similar solutions implemented in different languages and we use rotation adjusted target areas to render the expected areas.

Jeah something seems indeed off when setting a width and height.

Thanks for this already. Looks very promising.

**Comment by sungaila** [comment]
@ynnob [PDFtoImage 4.0.1](https://www.nuget.org/packages/PDFtoImage/4.0.1) fixed `Bounds` when used in conjunction with `Width`, `Height` and `Rotation`.

Please give it a try when you have time.

**Comment by ynnob** [comment]
Hey @sungaila 
I am testing again but i think something is still off. When setting the Width and Height the DPI is ignored. No matter what the dpi is set to the output does not change. When removing the Width/Height the dpi takes control again.

Is this supposed to happen? if so this should be documented and maybe you can explain what the individual settings really manipulate in the endresult.

Other than that this semms to correctly render the area. Nice 👍

**Comment by sungaila** [comment]
Hi @ynnob, this is intended behavior and is documented in the method XML comments (e.g. see IntelliSense in Visual Studio). You can either use DPI or set Width/Height, there is no combination of both like "use DPI for width but use this fixed height".
