### ISSUE TITLE
https://www.sungaila.de/PDFtoImage/  Conversion  loss  text

### ISSUE THREAD

**Issue by sibo-git** [sungaila/PDFtoImage#64]
### PDFtoImage version

3.0.0

### OS

Linux

### OS version

Ubuntu22.04

### Architecture

x64

### Framework

.NET (Core)

### App framework

Asp.NEt Core

### Detailed bug report

![image](https://github.com/sungaila/PDFtoImage/assets/56536667/4f23de48-aae7-414e-bb7d-ccf05836171e)
转换后丢失了好多数据

**Comment by sibo-git** [comment]
![image](https://github.com/sungaila/PDFtoImage/assets/56536667/38991266-0a24-47c5-8ddb-46314bdae8be)
source pdf file

**Comment by sibo-git** [comment]
Is it related to Chinese? I found that all Chinese characters have not been converted into images as part of the text.

**Comment by sungaila** [comment]
Hello @sibo-git, your problem might be related to this issue: #55 Sometimes the text is not rendered correctly if the output image is too big.

Have to tried to lower the DPI setting from `300` to something like `100`?

**Comment by sibo-git** [comment]
[内蒙古交科路桥建设有限公司加油站-96.00-2023年08月10日.pdf](https://github.com/sungaila/PDFtoImage/files/14063112/-96.00-2023.08.10.pdf)
the source file,

**Comment by sungaila** [comment]
Can confirm, the text is not rendered correctly. However, this seems to be a problem related to [PDFium](https://pdfium.googlesource.com/pdfium/) because the text is missing on Google Chrome and Microsoft Edge as well. So there is nothing I can do about it myself (this library is just a wrapper for PDFium).

Adobe Acrobat Reader renders the PDF just fine so this proves your PDF is not corrupted.

**Comment by sibo-git** [comment]
thanks,This issue only exists on Linux and not on Windows, so I am looking for a solution to add fonts to pdfium

**Comment by sungaila** [comment]
Unfortunately, this looks like a font issue in PDFium that I cannot build a workaround for. You can create a ticket on [the PDFium bugtracker](https://bugs.chromium.org/p/pdfium/issues/list) and hope someone gets this fixed.

Once a bugfix in PDFium was made, this library PDFtoImage will be updated and fixed as well.
