### ISSUE TITLE
Export to SVG

### ISSUE THREAD

**Issue by miminno** [sungaila/PDFtoImage#72]
### Question

Is it possible to draw a PDF onto the SKSvgCanvas to be able to export as SVG?

**Comment by sungaila** [comment]
Hi @miminno,

this library is intended for rasterizing PDFs into images. There is no support for vector graphics planned.

Technically, you could embed the generated SKBitmap in a SVG, but that would make hardly any sense.

**Comment by miminno** [comment]
Since Skia is used for rasterizing, it may as well be used for vectorizing ;) Embedding bitmap into an SVG surely doesn't make sense, but painting PDF over SVG Canvas and producing SVG is certainly achievable. Not sure how good the SVG support in Skia is, but that's a different issue.

**Comment by sungaila** [comment]
You can use `SKSvgCanvas` to draw your image and then export it to SVG, yes.

However, this library is based on top of [pdfium](https://pdfium.googlesource.com/pdfium/), which has no functions for extracting paths or other vector-related data from a PDF document.

**Comment by miminno** [comment]
pdfium has the ability to render a page to Skia: https://pdfium.googlesource.com/pdfium/+/main/public/fpdfview.h#940

**Comment by miminno** [comment]
At least we agreed that it was possible, albeit experimental.
