### ISSUE TITLE
In-Use memory increasing every time when you load a new page

### ISSUE THREAD

**Issue by Raja-1250** [sungaila/PDFtoImage#76]
### PDFtoImage version

4.0.0

### OS

Windows

### OS version

Hololens 2

### Architecture

arm64

### Framework

.NET Framework

### App framework

UWP

### Detailed bug report

Hi @sungaila 
The memory usage is consistently growing with each new page load, suggesting that certain unreferenced objects are not being properly disposed of in the code. Consequently, the application crashes after loading several pages. On Hololens 2, the crash occurs after loading 40 pages, with an observed increase of around 20 MB in used memory per new page. On an Android phone, the app crashes after loading 15 pages. It's worth noting that I'm setting the **_Encode quality to 1000_**. Below is the code snippet used for loading a page.

```   
 private async Task GetPage(int pageNo, MemoryStream pdfStream,OnPDFImageLoaded onPDFImageLoaded)
    {
        try
        {
            await Task.Run(() =>
            {
                MemoryStream imageStream = new MemoryStream();
                SKBitmap img = PDFtoImage.Conversion.ToImage(pdfStream, true, null, pageNo);
                img.Encode(imageStream, SKEncodedImageFormat.Png, quality);
                onPDFImageLoaded?.Invoke(true,"Success",imageStream);
            });
        }
        catch (Exception e)
        {
            onPDFImageLoaded?.Invoke(false, "Reason to fail:"+e.ToString(), null);
        }
    }
```

**Comment by Raja-1250** [comment]
@sungaila  I'm disposing the `imageStream`  in my caller method after consuming it, Using your suggested line of code didn't help, Also i've tried `img.Dispose()`, still no luck.

**Comment by sungaila** [comment]
What about `pdfStream`? You are calling `ToImage` with the parameter `leaveOpen: true` so you have to dispose this one somewhere as well.

**Comment by Raja-1250** [comment]
@sungaila  I load the PDF file into `pdfStream` just once for the entire session, and I dispose of it before closing the app. Therefore, it shouldn't cause in a consistent increase in the in-use memory value.

**Comment by sungaila** [comment]
I couldn't reproduce a memory leak with this simple setup:

```csharp
using var input = new FileStream("SocialPreview.pdf", FileMode.Open, FileAccess.Read);

for (int i = 0; i < 1000; i++)
{
    using var bitmap = PDFtoImage.Conversion.ToImage(input, leaveOpen: true);
}
```

<img width="767" alt="image" src="https://github.com/sungaila/PDFtoImage/assets/12021771/d7d259f0-3231-4936-87c2-1d318eddd100">

No idea how Unity handles the garbage collection, but if you are sure you dispose your two streams and one SKBitmap properly, maybe you could try to force collection yourself:

```csharp
GC.Collect(GC.MaxGeneration, GCCollectionMode.Forced);
```

**Comment by Raja-1250** [comment]
@sungaila I was able to resolve this issue by using `Resources.UnloadUnusedAssets()`. This API manually triggers the process of unloading assets like textures, models and etc that are no longer referenced by any active objects in the scene.
