### ISSUE TITLE
PDF image conversion error

### ISSUE THREAD

**Issue by xizhengchao** [sungaila/PDFtoImage#78]
### PDFtoImage version

4.0.1

### OS

Windows

### Architecture

x64

### Framework

.NET (Core)

### Detailed bug report

[1.pdf](https://github.com/sungaila/PDFtoImage/files/14747133/1.pdf)
PDF image conversion error. This PDF file is a bit large. How can this library solve the problem of converting images from such large files

**Comment by sungaila** [comment]
Hi @xizhengchao, thank you for opening this issue.

The dimensions of your PDF are extremely large. At default settings (300 DPI) this would result into an image size of 2,517,037 x 2,024,562 pixels.

You should specify either width or height so the resulting image won't be too large.

```csharp
using var inputPdf = new FileStream("1.pdf", FileMode.Open);
using var outputImage = new MemoryStream();

SavePng(outputImage, inputPdf, options: new(Width: 2000, WithAspectRatio: true, UseTiling: true));
```

In above example the image will be 2,000 pixels in width, the height is scaled down with the correct aspect ratio. The option `UseTiling` helps if you want to go for a bigger size.

**Comment by sungaila** [comment]
Please reopen this issue if the code above did not help.
