### ISSUE TITLE
UPM couldn't fetch

### ISSUE THREAD

**Issue by tugrulsubekci** [sungaila/PDFtoImage#80]
### PDFtoImage version

4.0.1

### OS

Windows

### Architecture

x64

### Framework

.NET Framework

### App framework

Unity

### Detailed bug report

Unity package manager sometimes couldn't fetch it properly and also if it achieves to load, it is so slow

**Comment by sungaila** [comment]
Hi @tugrulsubekci,

unfortunately, I cannot help here. I noticed that adding the Unity package takes a very long time (minutes on my machine for 126 MB of files) but it worked at least. [It looks like this problem also exists for others with the Unity Package Manager.](https://forum.unity.com/threads/installing-packages-from-git-through-upm-takes-longer-than-a-normal-download.1435360/)

It would be Unity's job to improve the performance of the UPM.
