### ISSUE TITLE
Converted Image is not having comments and Highlighted part 

### ISSUE THREAD

**Issue by NkhilKajrekar** [sungaila/PDFtoImage#89]
### PDFtoImage version

4.0.2

### OS

Windows

### Architecture

x64

### Framework

.NET (Core)

### App framework

.Net core

### Detailed bug report

[Presentation1.pdf](https://github.com/user-attachments/files/16123238/Presentation1.pdf)
In PDF we added comments and highlighted the part but after converting image it is not appearing in image
attached is pdf

**Comment by sungaila** [comment]
Hi @NkhilKajrekar,

you have to explicitly enable annotations by setting `WithAnnotations`. Something like this:

```csharp
SavePng(outputStream, inputStream, options: new(WithAnnotations: true);
```

**Comment by NkhilKajrekar** [comment]
Thanks its working
