### ISSUE TITLE
Consider making the PdfDocument struct public.

### ISSUE THREAD

**Issue by chrisg32** [sungaila/PDFtoImage#93]
### Detailed feature request

I am working on a project to render a pdf that has a lot of pages. I need to "recon" the document to get the number of pages and the sizes so that I can virtualize the process of getting the actual images. The `PdfDocument` struct would be perfect for this. Unfortunately, it is internal.

I understand the desire to keep the API simple but I feel there is a lot of value in exposing a few of the internals.

**Comment by sungaila** [comment]
Hi @chrisg32,

as described [in this previous issue](https://github.com/sungaila/PDFtoImage/issues/81#issuecomment-2135461739) I have no plans to make the internals public.

If you really REALLY want to access the PdfDocument class, you could use reflection like this:

```csharp
var document = PdfDocumentReflection.Load(inputStream, null, true);
var size = PdfDocumentReflection.PageSizes(document);

public static class PdfDocumentReflection
{
    private static readonly Type _pdfDocumentType = typeof(PDFtoImage.Conversion).Assembly.GetType("PDFtoImage.Internals.PdfDocument")!;

    private static readonly MethodInfo _loadMethod = _pdfDocumentType.GetMethod("Load", BindingFlags.Public | BindingFlags.Static)!;

    private static readonly PropertyInfo _pageSizesProperty = _pdfDocumentType.GetProperty("PageSizes", BindingFlags.Public | BindingFlags.Instance)!;

    public static object Load(Stream stream, string? password, bool disposeStream) => _loadMethod.Invoke(null, [stream, password, disposeStream])!;

    public static IList<SizeF> PageSizes(object pdfDocument) => (IList<SizeF>)_pageSizesProperty.GetValue(pdfDocument)!;
}
```

But I don't see why you can't just call `GetPageSize` and cache its result. For batching purposes you can use the new method overloads like:

`IEnumerable<SKBitmap> ToImages(Stream pdfStream, Range pages, bool leaveOpen = false, string? password = null, RenderOptions options = default)`
or
`IEnumerable<SKBitmap> ToImages(Stream pdfStream, IEnumerable<int> pages, bool leaveOpen = false, string? password = null, RenderOptions options = default)`

Alternatively, you might want to check out [PDFiumCore](https://github.com/Dtronix/PDFiumCore), which gives you to access the full potential of pdfium. PDFtoImage is just a small and simple API facade for conversion stuff.

**Comment by chrisg32** [comment]
@sungaila Thank you for the reply. Reflection was my fallback plan.

I appreciate your work on this library.
